---
#######################################
# Master Playbook for the setting up and reseting the Blockchain Automation Framework DLT network
#######################################
  - hosts: all
    gather_facts: no
    no_log: "{{ no_ansible_log | default(false) }}"
  - import_playbook: environment-setup.yaml   # First setup environment for each organization
  - import_playbook: kubernetes-env-setup.yaml # Then deploy Flux for each organization
    when: reset is undefined or reset == 'false'
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/deploy-network.yaml"
    vars:
      add_new_org: 'false'
    when: network.type == 'fabric' and (reset is undefined or reset == 'false')
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/chaincode-ops.yaml"
    vars:
      add_new_org: 'false'
    when: network.type == 'fabric' and (reset is undefined or reset == 'false')
  - import_playbook: "{{ playbook_dir }}/../../r3-corda/configuration/deploy-network.yaml"
    when: network.type == 'corda' and (reset is undefined or reset == 'false')
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-indy/configuration/deploy-network.yaml"
    when: network.type == 'indy' and (reset is undefined or reset == 'false')
  - import_playbook: "{{ playbook_dir }}/../../quorum/configuration/deploy-network.yaml"
    vars:
      add_new_org: false
    when: network.type == 'quorum' and (reset is undefined or reset == 'false')
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-besu/configuration/deploy-network.yaml"
    vars:
      add_new_org: false
    when: network.type == 'besu' and (reset is undefined or reset == 'false')
  - import_playbook: "{{ playbook_dir }}/../../r3-corda-ent/configuration/deploy-network.yaml"
    when: network.type == 'corda-enterprise' and (reset is undefined or reset == 'false')
    
# Reseting the network
  - import_playbook: "{{ playbook_dir }}/../../r3-corda/configuration/reset-network.yaml"
    when: network.type == 'corda' and reset is defined and reset == 'true'
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/reset-network.yaml"
    when: network.type == 'fabric' and reset is defined and reset == 'true'
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-indy/configuration/cleanup.yaml"
    when: network.type == 'indy' and reset is defined and reset == 'true'
  - import_playbook: "{{ playbook_dir }}/../../quorum/configuration/reset-network.yaml"
    when: network.type == 'quorum' and reset is defined and reset == 'true'
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-besu/configuration/reset-network.yaml"
    when: network.type == 'besu' and reset is defined and reset == 'true'
  - import_playbook: "{{ playbook_dir }}/../../r3-corda-ent/configuration/reset-network.yaml"
    when: network.type == 'corda-enterprise' and reset is defined and reset == 'true'
