# domain name of ordererorg
ordererorg_domain: "${AAIS_ORDERERORG_DOMAIN_NAME}"
# domain name of organization
domain: "${DOMAIN_NAME}"
# internal domain name from internal private hosted zone in route53
internal_domain: "${INTERNAL_DOMAIN_NAME}"
# pre-requistes image name to be used for the launch of openidl-baf pod
node_type: "aais"

network:
  # organization name to be used
  org_name: "${AAIS_ORGNAME}"
  # if true, this would deploy orderer organization
  # this would be true for aais and false for rest of the orgs
  ordererorg: "true"
  # name of the orderer organization
  ordererorg_name: "ordererorg"
  # list of organizations that will be part of the network
  # new organization should be added here to the list when a new organization is joining
  # the network with action=add_new_org
  organizations:
      # name of the new organization
    - name: "${ANALYTICS_ORGNAME}"
      # domain name of the new organization
      domain: "${ANALYTICS_DOMAIN_NAME}"
    - name: "${CARRIER_ORGNAME}"
      domain: "${CARRIER_DOMAIN_NAME}"
  # list of channels in which aais will be part of and aais to create for new channel for analytics, carrier nodes
  # new channel should be added here when there is a need to create a new channel and chaincode
  # related to the channel to be installed and committed
  channels:
    # common channel for all orgs
  - name: defaultchannel
    chaincode:
      # chaincode name to be used for installing and committing chaincode
      name: openidl-cc-default
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: "${CHAINCODE_REPO_BRANCH}"
      repo_path: openidl-chaincode/chaincode/openidl
    # name of the channel between analytics and carrier
  - name: ${ANAYTICS_CARRIER_CHANNEL_NAME}
    # chaincode details to be used to install and commit in the channel
    chaincode:
      # chaincode name
      name: openidl-cc-aais-carriers
      # github repo url from which the chaincode should be installed (public repository)
      repo_url: github.com/openidl-org/openidl-main.git
      # github repo branch from which the chaincode should be picked
      repo_branch: "${CHAINCODE_REPO_BRANCH}"
      # chaincode directory path in the github repo 
      repo_path: openidl-chaincode/chaincode/openidl
      # private data collection to be used while approving an committing the chaincode
      collectionconfig:
        # name of the private data collection
        name: "${ANALYTICS_ORGNAME}_${CARRIER_ORGNAME}_pdc"
        # policy to be used in private data collection
        policy: "OR('${ANALYTICS_ORGNAME}MSP.member', '${CARRIER_ORGNAME}MSP.member')"
    # channel for analytics and aais
  - name: ${ANAYTICS_AAIS_CHANNEL_NAME}
    # chaincode to be installed on analytics-aais channel
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: "${CHAINCODE_REPO_BRANCH}"
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        # private data collection for analytics and aais
        name: "${ANALYTICS_ORGNAME}_${AAIS_ORGNAME}_pdc"
        policy: "OR('${ANALYTICS_ORGNAME}MSP.member', '${AAIS_ORGNAME}MSP.member')"
