---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    run: ingress-default-backend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    run: haproxy-ingress
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.ports.http }}
    protocol: TCP
    targetPort: 80
    nodePort: 30100
  - name: https
    port: {{ .Values.service.ports.https }}
    protocol: TCP
    targetPort: 443
    nodePort: 30200
