apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: join-defaultchannel-aais-peer0
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: join-defaultchannel-aais-peer0
  chart:
    git: https://github.com/openidl-org/openidl-aais-gitops.git
    ref: baf-automation
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.dev.aais.techiething.com:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.aais.internal.techiething.com
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: defaultchannel      
    orderer:
      address: orderer1.ordererorg.dev.aais.techiething.com:8443
