#############################################################################################
# This role creates configtx.yaml file which is consumed by configtxgen tool
#############################################################################################

############################################################################################
# These tasks create the configtx.yaml file as the requirements mentioned in network.yaml 
# file. The configtx.yaml file is consumed by the configtxgen binary to generate the 
# genesis block and channels.

############################################################################################
# This task creates the build directory if it does not exist
- name: Create build directory if it does not exist
  file:
    path: "./build"
    state: directory

- name: "Remove old configtx file"
  file:
    path: "{{ config_file }}"
    state: absent
  tags:
    - molecule-idempotence-notest

# The tasks add the required data patch by patch to the configtx.yaml file to generate it.
- name: "create configtx.yaml file"
  file:
    path: "{{ config_file }}"
    state: touch
  tags:
    - molecule-idempotence-notest

- name: "Adding init patch to configtx.yaml"
  blockinfile:
    dest: "{{ config_file }}"
    block: "{{ lookup('template', 'configtxinit.tpl') }}"
    marker: "#"
  vars:
    consensus: "{{ org.services.consensus }}"
    org_query: "organizations[?type=='orderer']"
    org: "{{ network | json_query(org_query) | first }}"
  tags:
    - molecule-idempotence-notest

- name: "Adding organization patch to configtx.yaml"
  blockinfile:
    dest: "{{ config_file }}"
    block: "{{ lookup('template', 'configtxOrg.tpl') }}"
    marker: "#"
  vars:    
    component_name: "{{ item.name }}"
    component_ns: "{{ item.name | lower }}-net"
    component_type: "{{ item.type | lower }}"
    provider: "{{ network.env.proxy }}"
  loop: "{{ network['organizations'] }}"
  tags:
    - molecule-idempotence-notest

- name: "Adding orderer patch to configtx.yaml"
  blockinfile:
    dest: "{{ config_file }}"
    block: "{{ lookup('template', 'configtxOrderer.tpl') }}"
    marker: "#"
  vars:
    orderers: "{{ item.services.orderers }}"
    consensus: "{{ item.services.consensus }}"
    component_ns: "{{ item.name | lower }}-net"
    provider: "{{ network.env.proxy }}"
  loop: "{{ network['organizations'] }}"
  when: item.type == 'orderer'
  tags:
    - molecule-idempotence-notest

- name: "Adding profile patch to configtx.yaml"
  blockinfile:
    dest: "{{ config_file }}"
    block: "{{ lookup('template', 'configtxProfile.tpl') }}"
    marker: "#"
  vars:
    orderers: "{{ item.services.orderers }}"
    consensus: "{{ item.services.consensus }}"
    component_ns: "{{ item.name | lower }}-net"
  loop: "{{ network['organizations'] }}"
  when: network.channels is defined and item.type == 'orderer'
  tags:
    - molecule-idempotence-notest

- name: Display configtx file contents
  debug: 
    msg: "The configtx file is: {{ lookup('file', './build/configtx.yaml') }}"
