- name: Check build directory exists
  file:
   path: "./build"
   state: directory

- name: create collection config
  template:
    src: templates/collection-config.tpl
    dest: './build/collection-config-{{ item.channel_name }}.json'
  loop: "{{ collectionconfigs }}"
  loop_control:
    loop_var: collectionconfig
  when: collectionconfig.channel_name == item.channel_name

- name: convert to base64
  shell: |
    cat ./build/collection-config-{{ item.channel_name }}.json | base64 > ./build/collection-config-{{ item.channel_name }}.json.base64
