ordererorg_domain: ""
domain: ""
internal_domain: ""
add_org: "" 
node_type: ""
network:
  org_name: ""
  ordererorg: ""
  ordererorg_name: ""
  organizations:
    - name: ""
      domain: ""
      org_status: ""
  channels:
  - name: ""
    chaincode:
      name: ""
      repo_url: ""
      repo_branch: ""
      repo_path: ""
  - name: ""
    chaincode:
      name: ""
      repo_url: ""
      repo_branch: ""
      repo_path: ""
      collectionconfig:
        - name: ""
          policy: ""
