- hosts: ansible_provisioners
  gather_facts: yes
  no_log: "false"
  tasks:
    - include_role:
        name: "prerun-job"
      vars:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        aws_external_id: "{{ aws_external_id }}"
        aws_iam_role: "{{ aws_iam_role }}"

    - include_role:
        name: "openidl-secrets"
      vars:
        app_cluster_name: "{{ app_cluster_name }}"
        aws_region: "{{ aws_region }}"
        gitrepo_name: "{{ gitops_repo_url }}"
        gitrepo_branch: "{{ gitops_repo_branch }}"
        gitrepo_username: "{{ gitops_repo_user }}"
        gitrepo_password: "{{ gitops_repo_user_token }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_iam_role: "{{ aws_iam_role }}"
        org_name: "{{ org_name }}"
        env: "{{ env }}"
        vault_secret_name: "{{ vault_secret_name }}"
