# baf user access id for the aws account
access_id: ""
# baf user access secret key for the aws account
access_key: ""
# aws region where cluster
region: ""
# blockchain cluster name
cluster_name: ""
# aws account id
account: ""
# github openidl-aais-gitops repo url to be used for pushing fabric network configuration files
gitops_repo_url: "github.com/openidl-carrier1/openidl-aais-gitops"
# github openidl-aais-gitops repo branch to be used
gitops_repo_branch: "carrier_dev"
# github user with write access to push code
gitops_repo_user: ""
# github user personal access token
gitops_repo_user_token: ""
# github user email id
gitops_repo_user_email: ""
# domain name of ordererorg common across all nodes
ordererorg_domain: "openidl.aaisdirect.com"
# domain name of organization
domain: "carrier.hig.aaisdirect.com"
# internal domain name from internal private hosted zone in route53
internal_domain: "carrier.internal.hig.aaisdirect.com"
# environment for example: dev, test
env: "dev"
# new organization name to be added to the channel when action=add_new_org
add_org: ""
# pre-requistes image name to be used for the launch of openidl-baf pod
registry: ""
# chaincode version to be installed and committed
chaincode_version: ""
# type of the node, accepted: aais, analytics, carrier
node_type: "carrier"

network:
    # organization name to be used
    org_name: "hig"
    # if true, this would deploy orderer organization
    # this would be true for aais and false for rest of the orgs
    ordererorg: "false"
    # name of the orderer organization
    ordererorg_name: "ordererorg"
    # list of organizations that will be part of the network
    # new organization should be added here to the list when a new organization is joining
    # the network with action=add_new_org
    organizations:
        # name of the new organization
        - name: "hig"
          # domain name of the new organization
          domain: "carrier.hig.aaisdirect.com"
        # name of the new organization
        - name: "analytics"
          # domain name of the new organization
          domain: "analytics.aaisdirect.com"
    # channels list carrier will be part of and aais organization to create new channel for analytics, carrier nodes
    # to join new channel should be added and chaincode related to the channel to be installed and committed
    channels:
        # common channel for all orgs
        - name: defaultchannel
          chaincode:
              # chaincode name to be used for installing and committing chaincode
              name: openidl-cc-default
              repo_url: github.com/openidl-org/openidl-main.git
              repo_branch: "develop"
              repo_path: openidl-chaincode/chaincode/openidl
        # name of the channel between analytics and carrier
        - name: anal-hig
          # chaincode details to be used to install and commit in the channel
          chaincode:
              # chaincode name
              name: openidl-cc-aais-carriers
              # github repo url from which the chaincode should be installed (public repository)
              repo_url: github.com/openidl-org/openidl-main.git
              # github repo branch from which the chaincode should be picked
              repo_branch: "develop"
              # chaincode directory path in the github repo
              repo_path: openidl-chaincode/chaincode/openidl
              # private data collection to be used while approving an committing the chaincode
              collectionconfig:
                  # name of the private data collection
                  name: "analytics_hig_pdc"
                  # policy to be used in private data collection
                  policy: "OR('analyticsMSP.member', 'higMSP.member')"