- hosts: ansible_provisioners
  gather_facts: yes
  no_log: "{{ no_ansible_log | default(false) }}"
  vars_files:
    - "./{{ org_name }}-config-{{ env }}.yml"

  tasks:
    - include_role:
        name: "prerun-job"
      vars:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        aws_external_id: "{{ aws_external_id }}"
        aws_iam_role: "{{ aws_iam_role }}"

    - name: Update kubeconfig and set context to openidl EKS cluster
      shell: |
        export AWS_PROFILE=cicd-role; aws eks update-kubeconfig --region {{ aws_region }} --name {{ app_cluster_name }}

    - set_fact:
        user_token: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"
      when: deploy_action == "mongodb-deploy"

    - set_fact:
        root_token: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"
      when: deploy_action == "mongodb-deploy"

    - set_fact:
        user: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=16') }}"
      when: deploy_action == "mongodb-deploy"

    - include_role:
        name: "mongodb"
      vars:
        mongodb_user_token: "{{ user_token }}"
        mongodb_user: "{{ network.org_name }}-{{ env }}-{{ user }}"
        mongodb_root_token: "{{ root_token }}"
        mongodb_database: "openidl-offchain-db"
        deploy_action: "{{ deploy_action }}"


