- hosts: ec2-18-119-105-48.us-east-2.compute.amazonaws.com
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
    - set_fact:
        user_token: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"

    - set_fact:
        root_token: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"

    - set_fact:
        user: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=16') }}"

    - include_role:
        name: "prereqs"
      vars:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        aws_external_id: "{{ aws_external_id }}"
        aws_iam_role: "{{ aws_iam_role }}"
        cluster_name: "{{ app_cluster_name }}"

    - include_role:
        name: "mongodb"
      vars:
        mongodb_user_token: "{{ user_token }}"
        mongodb_user: "{{ network.org_name }}-{{ env }}-{{ user }}"
        mongodb_root_token: "{{ root_token }}"
        mongodb_database: "openidl-offchain-db"
