- hosts: ec2-18-119-105-48.us-east-2.compute.amazonaws.com
  gather_facts: no
  no_log: "{{ no_ansible_log | default(true) }}"
  tasks:
    - include_role:
        name: "prereqs"
      vars:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        aws_external_id: "{{ aws_external_id }}"
        aws_iam_role: "{{ aws_iam_role }}"
        cluster_name: "{{ blk_cluster_name }}"

    - name: Get vault root token
      shell: |
        export AWS_PROFILE=cicd-role
        aws secretsmanager get-secret-value --secret-id {{ network.org_name }}-{{ env }}-vault-unseal-key --version-stage AWSCURRENT | jq -r .SecretString
      register: vault

    - name: Get kvs user credentials from secrets manager
      shell: |
        export AWS_PROFILE=cicd-role
        aws secretsmanager get-secret-value --secret-id {{ network.org_name }}-{{ env }}-kvs-vault  --version-stage AWSCURRENT | jq -r '.SecretString|fromjson'.username
      register: vault_user

    - name: Get kvs user credentials from secrets manager
      shell: |
        export AWS_PROFILE=cicd-role
        aws secretsmanager get-secret-value --secret-id {{ network.org_name }}-{{ env }}-kvs-vault  --version-stage AWSCURRENT | jq -r '.SecretString|fromjson'.password
      register: vault_user_token

    - set_fact:
        ca_user_password: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"

    - include_role:
        name: "baf/pre-register-users"
      vars:
        vault_token: "{{ vault.stdout }}"
        vault_kvs_user: "{{ vault_user.stdout }}"
        vault_kvs_user_token: "{{ vault_user_token.stdout }}"
        ca_user_token: "{{ ca_user_password }}"
