- hosts: ec2-18-119-105-48.us-east-2.compute.amazonaws.com
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
    - name: Get KMS ID
      shell: |
        export AWS_PROFILE=cicd-role; aws kms describe-key --key-id alias/{{ network.org_name[:4] }}-{{ env }}-vault-kmskey | jq -r .KeyMetadata.KeyId
      register: output
    
    - set_fact:
        config_user: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - set_fact:
        config_user_token: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"

    - set_fact:
        kvs_user: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - set_fact:
        kvs_user_token: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"

    - include_role:
        name: "prereqs"
      vars:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        aws_external_id: "{{ aws_external_id }}"
        aws_iam_role: "{{ aws_iam_role }}"
        cluster_name: "{{ blk_cluster_name }}"

    - include_role:
        name: "vault"
      vars:
        vault_kms_key_id: "{{ output.stdout }}"
        vault_config_user: "config-{{ network.org_name }}-{{ config_user }}"
        vault_config_user_token: "{{ config_user_token }}"
        vault_kvs_user: "kvs-{{ network.org_name }}-{{ config_user }}"
        vault_kvs_user_token: "{{ kvs_user_token }}"
