apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: approve-defaultchannel-openidl-cc-default-2-1
  namespace: analytics-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: approve-defaultchannel-openidl-cc-default-2-1
  chart:
    git: https://github.com/openidl-org/openidl-aais-gitops.git
    ref: baf-automation
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: analytics-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.analytics-net:7051
      localmspid: analyticsMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.dev.analytics.internal.techiething.com
      authpath: devanalytics-net-auth
      adminsecretprefix: analytics/crypto/peerOrganizations/analytics-net/users/admin 
      orderersecretprefix: analytics/crypto/peerOrganizations/analytics-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.ordererorg.dev.aais.techiething.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.3
      name: openidl-cc-default
      version: 2
      sequence: 1
      commitarguments: ''
      endorsementpolicies:  ''
      usecollectionconfig: false
    channel:
      name: defaultchannel
