apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: install-openidl-cc-default-
  namespace: analytics-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: install-openidl-cc-default-
  chart:
    git: https://github.com/openidl-org/openidl-aais-gitops.git
    ref: baf-automation
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: analytics-net
      network:
        version: 2.2.3
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.analytics-net:7051
      localmspid: analyticsMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.dev.analytics.internal.techiething.com
      authpath: devanalytics-net-auth
      adminsecretprefix: analytics/crypto/peerOrganizations/analytics-net/users/admin 
      orderersecretprefix: analytics/crypto/peerOrganizations/analytics-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: analytics/credentials/analytics-net/git?git_password
      tls: false
    orderer:
      address: orderer1.ordererorg.dev.aais.techiething.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.3
      name: openidl-cc-default
      version: 
      lang: golang
      maindirectory: main
      repository:
        hostname: "github.com"
        git_username: ""
        url: github.com/openidl-org/openidl-main.git
        branch: cognito-fabric-node14-helm
        path: openidl-chaincode/chaincode/openidl
      endorsementpolicies:  ''
