---
dependency:
  name: galaxy
driver:
  name: docker
lint: |   
  yamllint .
platforms:
  - name: kind-default
    groups:
    - k8s
    image: bsycorp/kind:latest-1.16
    privileged: True
    override_command: no
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-10443}:8443/tcp
    pre_build_image: yes
  - name: vault-default                         # This is the ansible inventory group
    image: index.docker.io/vault:1.7.0
    privileged: True
    override_command: True
    command: server -dev -dev-root-token-id="root"
    exposed_ports:
      - 8200/tcp
    published_ports:
      - 0.0.0.0:9090:8200/tcp    # Map exposed ports to localhost
    pre_build_image: yes
provisioner:
  name: ansible
  log: True
  lint: |
    ansible-lint
  env:
    K8S_AUTH_KUBECONFIG: /tmp/molecule/kind-default/kubeconfig
    KUBECONFIG: /tmp/molecule/kind-default/kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles:${MOLECULE_PROJECT_DIRECTORY}/../roles:${MOLECULE_PROJECT_DIRECTORY}/../../../shared/roles
    KIND_PORT: '${TEST_CLUSTER_PORT:-10443}'
verifier:
  name: ansible
  lint: |
    ansible-lint
