charts:
  ca-orderer: ca
  ca-peer: ca
  ca-tools: catools
  cas: ca
  orderers: orderernode
  zkkafka: zkkafka
  peers: peernode
  value_peer: peernode
  create_channel_job: create_channel
  join_channel_job: join_channel
  anchorpeer_job: anchorpeer
  install_chaincode_job: install_chaincode
  instantiate_chaincode_job: instantiate_chaincode
  invoke_chaincode_job: invoke_chaincode
  upgrade_chaincode_job: upgrade_chaincode
  nms: nms
  mongodb: mongodb
  doorman: doorman
  notarydb: h2
  nodedb: h2
  db: h2
  notaryjob: notary-initial-registration
  nodejob: node-initial-registration
  notarynode: notary
  nodenode: node
  tessera: node_tessera
  constellation: node_constellation
  pki-generator: generate-pki
  pki-generator-node: generate-pki-node
  signer: signer
  node_orion: node_orion
  idman: idman
  validator: node_validator
  nmap: nmap
  notary-initial-registration: notary-initial-registration
  notary: notary
  bridge: bridge
  float: float
  node_registration: node-initial-registration
  cli: fabric_cli
  commit_chaincode_job: commit_chaincode 
  approve_chaincode_job: approve_chaincode
  node: node
  crypto_orion: orion_key_mgmt
  crypto_tessera: tessera_key_mgmt
  node_besu: node_besu
