---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.peer.name }}-db-volume
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.peer.name }}-db-volume
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.pvc }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}          
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.couchdb.storageclassname }}
  resources:
    requests:
      storage: {{ .Values.storage.couchdb.storagesize }}
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.peer.name }}-peer-volume
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.peer.name }}-db-volume
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- if $.Values.annotations }}
    {{- range $key, $value := $.Values.annotations.pvc }}
    {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}          
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.peer.storageclassname }}
  resources:
    requests:
      storage: {{ .Values.storage.peer.storagesize }}
