# Check peer msp already created
- name: Check if peer msp already created
  shell: |
    vault kv get -format=yaml {{ vault.secret_path | default('secret') }}/crypto/peerOrganizations/{{ component_name }}/peers/{{ peer.name }}.{{ component_name }}/msp
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  register: vault_msp_result
  ignore_errors: yes
  changed_when: false

# Get MSP info
- name: Get MSP info
  include_role: 
    name: "setup/get_crypto"
  vars:
    vault_output: "{{ vault_msp_result.stdout | from_yaml }}"
    type: "peer"
    msp_path: "./build/crypto-config/peerOrganizations/{{ component_name }}/peers/{{ peer.name }}.{{ component_name}}/msp"
  when: vault_msp_result.failed == False
  tags:
    - molecule-idempotence-notest
