global:
    clusterurl: carrierdemo.com
    appsecret: apps-secret
    configpath: config-local-carrier
    datacallapp:
        install: true
        port: 8080
        targetport: 8080
        servicename: data-call-app-service
        ingressenabled: false
        ingresshostname: data-call-app-service.dev.carrier.internal.hig1.aaisdirect.com
        publicingresshostname: data-call-app-service.dev.carrier.hig1.aaisdirect.com
        image:
            repository: ghcr.io/openidl-org/openidl-data-call-app
            pullPolicy: IfNotPresent
            tag: 9-cognito-fabric-node14-helm-f84a367-093020211950
    utilities:
        install: true
        port: 8080
        targetport: 8080
        servicename: utilities-service
        ingressenabled: false
        ingresshostname: utilities-service.dev.carrier.internal.hig1.aaisdirect.com
        publicingresshostname: utilities-service.dev.carrier.hig1.aaisdirect.com
        image:
            repository: ghcr.io/openidl-org/openidl-utilities
            pullPolicy: IfNotPresent
            tag: 17-cognito-fabric-node14-helm-f84a367-093020211950
    carrierui:
        install: true
        servicename: carrier-ui-service
        port: 8080
        targetport: 8080
        ingressenabled: false
        ingresshostname: openidl.dev.carrier.hig1.aaisdirect.com
        image:
            repository: ghcr.io/openidl-org/openidl-carrier-ui
            pullPolicy: IfNotPresent
            tag: 9-cognito-fabric-node14-helm-f84a367-093020211950
    insurancedatamanager:
        install: true
        port: 8080
        targetport: 8080
        servicename: insurance-data-manager-service
        ingressenabled: false
        ingresshostname: insurance-data-manager-service.dev.carrier.hig1.aaisdirect.com
        image:
            repository: ghcr.io/openidl-org/openidl-insurance-data-manager
            pullPolicy: IfNotPresent
            tag: 5-cognito-fabric-node14-helm-f84a367-093020211950
    datacallprocessor:
        install: true
        port: 8080
        targetport: 8080
        servicename: data-call-processor-service
        image:
            repository: ghcr.io/openidl-org/openidl-data-call-processor
            pullPolicy: IfNotPresent
            tag: 5-cognito-fabric-node14-helm-f84a367-093020211950
    upload:
        install: true
        port: 80
        targetport: 80
        servicename: upload-service
        image:
            repository: ghcr.io/openidl-org/openidl-upload
            pullPolicy: IfNotPresent
            tag: latest
    datacallmoodlistener:
        install: false
        port: 8080
        targetport: 8080
        servicename: data-call-mood-listener-service
        image:
            repository: ghcr.io/openidl-org/openidl-data-call-mood-listener
            pullPolicy: IfNotPresent
            tag: 5-cognito-fabric-node14-helm-f84a367-093020211950
    transactionaldataeventlistener:
        install: false
        port: 8080
        targetport: 8080
        servicename: transactional-data-event-listener-service
        image:
            repository: ghcr.io/openidl-org/openidl-transactional-data-event-listener
            pullPolicy: IfNotPresent
            tag: 5-cognito-fabric-node14-helm-f84a367-093020211950
    ui:
        install: false
        servicename: ui-service
        port: 8080
        targetport: 8080
        ingressenabled: false
        ingresshostname: openidl.dev.carrier.hig1.aaisdirect.com
        image:
            repository: ghcr.io/openidl-org/openidl-ui
            pullPolicy: IfNotPresent
            tag: 9-cognito-fabric-node14-helm-f84a367-093020211950
    secrets:
        install: true
