apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hig1-peer0
  namespace: hig1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: hig1-peer0
  chart:
    git: https://github.com/openidl-carrier1/openidl-aais-gitops
    ref: carrier_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: hig1-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.hig1-net.hig1.dev.carrier.hig1.aaisdirect.com:8443
      gossipexternalendpoint: peer0.hig1-net.hig1.dev.carrier.hig1.aaisdirect.com:8443
      localmspid: hig1MSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.3
      couchdb:
        username: hig1-user

    storage:
      peer:
        storageclassname: hig1sc
        storagesize: 50Gi
      couchdb:
        storageclassname: hig1sc
        storagesize: 50Gi

    vault:
      role: vault-role
      address: http://vault.dev.carrier.internal.hig1.aaisdirect.com
      authpath: devhig1-net-auth
      secretprefix: hig1/crypto/peerOrganizations/hig1-net/peers/peer0.hig1-net
      secretambassador: hig1/crypto/peerOrganizations/hig1-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: hig1/credentials/hig1-net/couchdb/hig1?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: hig1.dev.carrier.hig1.aaisdirect.com
