metadata:
  #Provide the namespace for CA deployment
  #Eg. namespace: example-com
  namespace: 
  #Provide name for ca server deployment
  #Eg. name: ca-tools
  name:
# Provide the number of replica pods
replicaCount: 1

image:
  #Provide the image name for the server container
  #Eg. image: hyperledger/fabric-ca-tools
  repository: 
  #Provide the image tag for the server container
  #Eg. imagetag: 1.3.0
  tag: 
  # Provide image pull policy
  pullPolicy: IfNotPresent

annotations:
  #Extra annotations
  pvc: {}
  deployment: {}
  
storage:
  #Provide the storageclassname for 
  #Eg. storageclassname: aws-storage
  storageclassname: 
  #Provide the storagesize for CA
  #Eg. storagesize: 512Mi
  storagesize: 

