# Default values for haproxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  namespace: ingress-controller

image:
  defaultbackend: gcr.io/google_containers/defaultbackend:1.0
  haproxy: quay.io/jcmoraisjr/haproxy-ingress
  version: v0.9.1

service:
  type: LoadBalancer
  ports:
    http: 80
    https: 443
