#############################################################################################
# This role creates value file for zkKafka and orderer
#############################################################################################


############################################################################################
# This task creates the value file for kafka for orderes as per requirements mentioned in
# network.yaml
- name: "create kafka clusters"
  include_role:
    name: helm_component
  vars:
    name: "orderer"
    org_name: "{{ item.name | lower }}"
    kafka_image: "hyperledger/fabric-kafka:{{ kafka_image_version[network.version] }}"
    zookeeper_image: "hyperledger/fabric-zookeeper:{{ zookeeper_image_version[network.version] }}"
    component_name: "zkkafka"
    type: "zkkafka"
    consensus: "{{component_services.consensus}}"
  when: component_services.consensus.name == 'kafka' and component_services.consensus is defined

############################################################################################
# This task creates the value file for the Orderers as per requirements mentioned in 
# network.yaml
- name: "create orderers"
  include_role:
    name: helm_component
  vars:
    name: "orderer"
    org_name: "{{ item.name | lower }}"
    component_name: "{{ orderer.name }}-{{ org_name }}"
    orderer_image: "hyperledger/fabric-orderer:{{ network.version }}"
    alpine_image: "{{ docker_url }}/alpine-utils:1.0"
    type: "orderers"
    consensus: "{{component_services.consensus}}"
    genesis: "{{ lookup('file', '{{ build_path }}/channel-artifacts/genesis.block.base64') }}"
  loop: "{{ component_services.orderers }}"
  loop_control:
    loop_var: orderer
  when: 
    - component_services.orderers is defined and component_services.consensus is defined
    - orderer.status is not defined or orderer.status == 'new'

#Git Push : Pushes the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../.."
    gitops: "{{ item.gitops }}"
    GIT_RESET_PATH: "platforms/hyperledger-fabric/configuration"
    msg: "[ci skip] Pushing Orderer files"
  tags:
    - notest
