{{- if .Values.global.datacallapp.install }}
{{- if .Values.global.datacallapp.ingressenabled }}
{{- $fullName := include "openidl-data-call-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-call-app-ingress
  labels:
    {{- include "openidl-data-call-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.global.datacallapp.ingresshostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.datacallapp.servicename }}
                port: 
                  number: {{ .Values.global.datacallapp.port }}
    - host: {{ .Values.global.datacallapp.publicingresshostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.datacallapp.servicename }}
                port: 
                  number: {{ .Values.global.datacallapp.port }}
{{- end }}
{{- end }}
