---
############################################################################################
# This role creates the invoke_chaincode value file

# Check or Wait if commit-chaincode is already run for v.2.x
- name: "Waiting for chaincode to be commited on {{ peer.name }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Job"
    namespace: "{{ org.name |lower }}-net"
    kubernetes: "{{ org.k8s }}"
    component_name: "commit-{{item.channel_name|lower}}-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}-{{ peer.chaincode.sequence | default('1') }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: 
    - peer.chaincode is defined and '2.' in network.version
    - add_new_org is not defined or add_new_org == 'false'
  tags:
    - commit
# Check or Wait if approve-chaincode is already run for v.2.x when adding a new org
- name: "Waiting for chaincode to be approved on {{ peer.name }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Job"
    namespace: "{{ org.name |lower }}-net"
    kubernetes: "{{ org.k8s }}"
    component_name: "approve-{{item.channel_name|lower}}-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}-{{ peer.chaincode.sequence | default('1') }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: 
    - peer.chaincode is defined and '2.' in network.version 
    - add_new_org is defined and add_new_org == 'true'
  tags:
    - commit

# Check or Wait if install-chaincode is already run for v.1.4.x
- name: "Waiting for chaincode to be installed on {{ peer.name }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Job"
    namespace: "{{ org.name |lower }}-net"
    kubernetes: "{{ org.k8s }}"
    component_name: "install-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: peer.chaincode is defined and '1.4' in network.version 
  tags:
    - commit


# Check if invoke-chaincode is already run
- name: 'Check for invoke-chaincode job'
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "OneTimeJob"
    namespace: "{{ org.name |lower }}-net"
    kubernetes: "{{ org.k8s }}"
    component_name: "invoke-{{item.channel_name|lower}}-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  register: invoke_chaincode
  when: peer.chaincode is defined

- name: "Set Variable invoke_chaincode"
  set_fact:
    invoke_chaincode: "{{ result }}"

  
- name: "Write all endorsing orgs certificates to vault"
  include_tasks: write.yaml
  vars:
    namespace: "{{ org.name |lower }}-net"
    vault: "{{ org.vault }}"
    peers: "{{ organization.services.peers | first }}"
  loop: "{{ network.organizations }}"
  loop_control:
    loop_var: organization
  when: organization.type == 'peer' and '2.' in network.version

# Nested task for chanincode invocation
- name: "Create value file for chaincode invocation"
  include_role:
    name: helm_component
  vars:    
    name: "{{ org.name | lower }}"
    type: "invoke_chaincode_job"
    component_name: "invoke-{{item.channel_name|lower}}-{{peer.chaincode.name}}-{{peer.chaincode.version}}"
    namespace: "{{ org.name |lower }}-net"
    peer_name: "{{ peer.name }}"
    peer_address: "{{ peer.name }}.{{ org.name |lower }}-net:{{ peer.grpc.port }}"
    git_url: "{{ org.gitops.git_url }}"
    git_branch: "{{ org.gitops.branch }}"
    charts_dir: "{{ org.gitops.chart_source }}"
    vault: "{{ org.vault }}"
    fabrictools_image: "hyperledger/fabric-tools:{{ network.version }}"
    alpine_image: "{{ docker_url }}/alpine-utils:1.0"
    component_chaincode: "{{ peer.chaincode }}"
    values_dir: "{{playbook_dir}}/../../../{{org.gitops.release_dir}}/{{ org.name | lower }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: 
    - peer.chaincode is defined
    - invoke_chaincode.resources|length == 0 or add_new_org == 'true'

#Git Push : Pushes the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../.."
    gitops: "{{ org.gitops }}"
    GIT_RESET_PATH: "platforms/hyperledger-fabric/configuration"
    msg: "[ci skip] Pushing chaincode invocation files"
  when: invoke_chaincode.resources|length == 0 or add_new_org == 'true'
