#############################################################################################
#                      This role deletes the channel artifacts                              #       
#############################################################################################

# This task deletes the BASE 64 encoded genesis blocks for all channels
- name: Delete genesis block from Vault
  shell: |
    vault delete {{ item.vault.secret_path | default('secret') }}/crypto/ordererOrganizations/{{ component_name }}
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  ignore_errors: yes
