---
- name: Verify
  hosts: localhost
  connection: local
  vars:
    bin_install_dir: "~/bin"
    kubeconfig_path: "/tmp/molecule/kind-default/kubeconfig"
    kubecontext: "kind"
    network:
      env:
        type: test
  tasks:
  # Assert Flux is installed on Kubernetes
  - name: Check Flux on Kubernetes clusters
    k8s_info:
      kind: Pod
      namespace: flux-{{ network.env.type }}
      kubeconfig: "{{ kubeconfig_path }}"
      context: "{{ kubecontext }}"
      label_selectors:
        - app = flux
        - release = flux-{{ network.env.type }}
      field_selectors:
        - status.phase=Running
    register: flux_service
  - name: Assert Flux has been installed
    assert:
      that: flux_service.resources|length == 1
  - name: Check Haproxy on Kubernetes clusters
    k8s_info:
      kind: Pod
      namespace: "ingress-controller"
      kubeconfig: "{{ kubeconfig_path }}"
      context: "{{ kubecontext }}"
      label_selectors:
        - run = haproxy-ingress
      field_selectors:
        - status.phase=Running
    register: haproxy_status
  - name: Assert HAproxy has been installed
    assert:
      that: haproxy_status.resources|length == 1
