###########################################################################################
# This task calls nested_sign_and_update and nested_update_channel tasks
############################################################################################


# Creator signs the config block and updates the channel with latest config block  
- name: Call nested_update_channel for the peer
  include_tasks: nested_update_channel.yaml
  vars:
    channel_name: "{{ item.channel_name | lower }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    peer: "{{ participant.peers | first }}"
  loop: "{{ participants }}"
  loop_control:
    loop_var: participant
  when: participant.type == 'creator'
