{{- if .Values.global.secrets.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appsecret }}
data:
  {{- $files := .Files }}
  {{ $configpath := print .Values.global.configpath "/" }}
  {{- range .Values.secrets }}
    {{- if eq .namespace "default" }}
    {{ $path := .file | replace "config/" $configpath }}
    {{ .name }}: |-
      {{ ($files.Get $path) | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}