# call nested install for each org from network.org that is also in participants list
- name: "Call nested  main from here"
  include_tasks: nested_install.yaml
  vars:
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
  loop: "{{ participants }}"
  loop_control: 
    loop_var: participant
  when: 
  - org.type == 'peer'
  - participant.org_status == 'new' or participant.peerstatus is not defined or participant.peerstatus == 'new'
