#############################################################################################
# This role creates the value file for peers of organisations and write couch db credentials
# to the vault.
#############################################################################################

###########################################################################################
# This task writes the couchdb credentials for each organization to the vault
- name: Write the couchdb credentials to Vault
  shell: |
    vault write {{ vault.secret_path | default('secret') }}/credentials/{{ namespace }}/couchdb/{{ item.name | lower}} user="admin123"
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  tags:
    - molecule-idempotence-notest

############################################################################################
# This task is the nested task for main.yaml which helps to iterate over all peers
- name: Create Value files for Organization Peers
  include_role:
    name: helm_component
  vars:
    name: "{{ item.name | lower }}"
    type: "value_peer"
    component_name: values-{{ peer.name }}
    couchdb_image: "{{ couchdb_image_version[network.version] }}"
    peer_image: "hyperledger/fabric-peer:{{ network.version }}"
    alpine_image: "{{ docker_url }}/alpine-utils:1.0"
    peer_name: "{{ peer.name }}"
    peer_ns: "{{ namespace }}"
    provider: "{{ network.env.proxy }}"
  loop: "{{ component_services.peers }}"
  loop_control:
    loop_var: peer 
  when: peer.peerstatus is not defined or peer.peerstatus == 'new'

#Git Push : Pushes the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../.."
    gitops: "{{ item.gitops }}"
    GIT_RESET_PATH: "platforms/hyperledger-fabric/configuration"
    msg: "[ci skip] Pushing Peer files"
  tags:
    - notest

# Wait for peer pods to be in the state of running
- name: "Waiting for peer pod {{ peer.name }} in {{ item.name | lower }}-net"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ item.name | lower }}-net"
    component_name: "{{ peer.name }}"
    kubernetes: "{{ item.k8s }}"
    label_selectors:
      - app = {{ component_name }}
  loop: "{{ component_services.peers }}"
  loop_control:
    loop_var: peer 
  when: peer.peerstatus is not defined or peer.peerstatus == 'new'
  tags:
    - notest
