---
dependencies:
  - role: "aws-auth"
    vars:
      aws_authenticator:
        version: "1.10.3"
        release_date:  "2018-07-26"
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
        checksum: ""
      kubeconfig_path: "{{ item.k8s.config_file }}"
      kubecontext: "{{ item.k8s.context }}"
    when: item.cloud_provider == 'aws'
  - role: "helm"
    vars:
      helm:
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
        checksum: ""
  - role: "kubectl"
    vars:
      kubectl:
        version: "1.16.13"
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
        checksum: "sha256:170bee26f53829c8917fad343fd10b0b9bcd47dc296c14604b6b28e6c3cec08c"
