- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
    - name: delete vault secrets from aws secret manager
      shell: |
        aws secretsmanager delete-secret --secret-id {{ network.org_name }}-{{ env }}-mongodb-user --force-delete-without-recovery
        aws secretsmanager delete-secret --secret-id {{ network.org_name }}-{{ env }}-mongodb-user-token --force-delete-without-recovery
        aws secretsmanager delete-secret --secret-id {{ network.org_name }}-{{ env }}-mongodb-root-token --force-delete-without-recovery
      register: output
      ignore_errors: yes
    
    - name: delete mongodb helm install
      shell: |
        helm -n database delete {{ network.org_name }}
      register: mongodb

    - debug:
        msg: "{{ mongodb }}"
