- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(true) }}"
  tasks:
    - name: Get vault root token
      shell: |
        aws secretsmanager get-secret-value --secret-id {{ network.org_name }}-{{ env }}-vault-unseal-key --version-stage AWSCURRENT | jq -r .SecretString
      register: vault

    - name: Get kvs user credentials from secrets manager
      shell: |
        aws secretsmanager get-secret-value --secret-id {{ network.org_name }}-{{ env }}-kvs-vault  --version-stage AWSCURRENT | jq -r '.SecretString|fromjson'.username
      register: vault_user

    - name: Get kvs user credentials from secrets manager
      shell: |
        aws secretsmanager get-secret-value --secret-id {{ network.org_name }}-{{ env }}-kvs-vault  --version-stage AWSCURRENT | jq -r '.SecretString|fromjson'.password
      register: vault_user_token

    - set_fact:
        ca_user_password: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"

    - include_role:
        name: "baf/pre-register-users"
      vars:
        vault_token: "{{ vault.stdout }}"
        vault_kvs_user: "{{ vault_user.stdout }}"
        vault_kvs_user_token: "{{ vault_user_token.stdout }}"
        ca_user_token: "{{ ca_user_password }}"
