access_id: ""
access_key: ""
region: ""
cluster_name: ""
account: ""
gitops_repo_url: "github.com/openidl-org/openidl-aais-gitops.git"
gitops_repo_branch: "baf-automation"
gitops_repo_user: ""
gitops_repo_user_token: ""
gitops_repo_user_email: ""
ordererorg_domain: "aais.techiething.com"
domain: "trv.techiething.com"
internal_domain: "trv.internal.techiething.com"
env: "dev"
add_org: "" 
registry: ""
chaincode_version: ""
node_type: "carrier"

network:
  org_name: "trv"
  ordererorg: "false"
  ordererorg_name: "ordererorg"
  organizations:
    - name: ""
      domain: ""
      org_status: ""
  channels:
  - name: analytics-trv
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: cognito-fabric-node14-helm
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        name: "analytics_trv_pdc"
        policy: "OR('analyticsMSP.member', 'trvMSP.member')"
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: cognito-fabric-node14-helm
      repo_path: openidl-chaincode/chaincode/openidl
